[2017-Jul-14 12:46] 127.0.0.1 GET http /? 200 OK
[2017-Jul-14 12:46] 127.0.0.1 GET http /static/css/skeleton.css? 304 NOT MODIFIED
[2017-Jul-14 12:46] 127.0.0.1 GET http /static/css/normalize.css? 304 NOT MODIFIED
[2017-Jul-14 12:46] 127.0.0.1 GET http /static/css/main.css? 304 NOT MODIFIED
[2017-Jul-14 12:46] 127.0.0.1 GET http /favicon.ico? 404 NOT FOUND
[2017-Jul-14 12:46] 127.0.0.1 GET http /favicon.ico? 404 NOT FOUND
[2017-Jul-14 12:46] 127.0.0.1 GET http /analytics/bb? 200 OK
[2017-Jul-14 12:49] 127.0.0.1 GET http /? 200 OK
[2020-May-18 08:39] 36.73.34.62 GET http /? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 66, in index
    cursor.execute(list_sql)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'hanoman.WEB_URL' doesn't exist")

[2020-May-18 08:39] 36.73.34.62 GET http /? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 66, in index
    cursor.execute(list_sql)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'hanoman.WEB_URL' doesn't exist")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1822, in handle_user_exception
    return handler(e)
  File "app.py", line 191, in exceptions
    return make_response(e , 405)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/helpers.py", line 223, in make_response
    return current_app.make_response(args)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 2131, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a ProgrammingError.

[2020-May-18 08:39] 36.73.34.62 GET http /? 405 METHOD NOT ALLOWED
[2020-May-18 08:39] 36.73.34.62 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 130, in reroute
    if platform in platform_dict.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'

[2020-May-18 08:39] 36.73.34.62 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 130, in reroute
    if platform in platform_dict.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1822, in handle_user_exception
    return handler(e)
  File "app.py", line 191, in exceptions
    return make_response(e , 405)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/helpers.py", line 223, in make_response
    return current_app.make_response(args)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 2131, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a AttributeError.

[2020-May-18 08:39] 36.73.34.62 GET http /favicon.ico? 405 METHOD NOT ALLOWED
[2020-May-18 08:48] 36.73.34.62 GET http /? 200 OK
[2020-May-18 08:48] 36.73.34.62 GET http /static/css/normalize.css? 200 OK
[2020-May-18 08:48] 36.73.34.62 GET http /static/css/main.css? 200 OK
[2020-May-18 08:48] 36.73.34.62 GET http /static/css/skeleton.css? 200 OK
[2020-May-18 08:52] 36.73.34.62 GET http /? 200 OK
[2020-May-18 08:52] 36.73.34.62 GET http /static/css/skeleton.css? 200 OK
[2020-May-18 08:52] 36.73.34.62 GET http /static/css/normalize.css? 200 OK
[2020-May-18 08:52] 36.73.34.62 GET http /static/css/main.css? 200 OK
[2020-May-18 08:52] 36.73.34.62 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 130, in reroute
    if platform in platform_dict.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'

[2020-May-18 08:52] 36.73.34.62 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 130, in reroute
    if platform in platform_dict.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1822, in handle_user_exception
    return handler(e)
  File "app.py", line 191, in exceptions
    return make_response(e , 405)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/helpers.py", line 223, in make_response
    return current_app.make_response(args)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 2131, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a AttributeError.

[2020-May-18 08:52] 36.73.34.62 GET http /favicon.ico? 405 METHOD NOT ALLOWED
[2020-May-18 08:54] 36.73.34.62 GET http /? 200 OK
[2020-May-18 08:54] 36.73.34.62 GET http /? 200 OK
[2020-May-18 08:57] 36.73.34.62 POST http /? 200 OK
[2020-May-18 08:57] 36.73.34.62 POST http /? 200 OK
[2020-May-18 08:57] 36.73.34.62 GET http /? 200 OK
[2020-May-18 08:58] 36.73.34.62 POST http /? 200 OK
[2020-May-18 09:01] 36.73.34.62 GET http /? 200 OK
[2020-May-18 09:01] 36.73.34.62 POST http /? 200 OK
[2020-May-20 03:34] 36.65.144.197 GET http /? 200 OK
[2020-May-20 03:34] 36.65.144.197 GET http /static/css/skeleton.css? 304 NOT MODIFIED
[2020-May-20 03:34] 36.65.144.197 GET http /static/css/normalize.css? 304 NOT MODIFIED
[2020-May-20 03:34] 36.65.144.197 GET http /static/css/main.css? 200 OK
[2020-May-20 03:34] 54.227.20.204 GET http /? 200 OK
[2020-May-20 03:34] 36.73.28.12 GET http /? 200 OK
[2020-May-20 03:34] 36.73.28.12 GET http /static/css/skeleton.css? 200 OK
[2020-May-20 03:34] 36.73.28.12 GET http /static/css/normalize.css? 200 OK
[2020-May-20 03:34] 36.73.28.12 GET http /static/css/main.css? 200 OK
[2020-May-20 03:34] 36.73.28.12 GET http /robots.txt? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "appl.py", line 130, in reroute
    if platform in platform_dict.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'

[2020-May-20 03:34] 36.73.28.12 GET http /robots.txt? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "appl.py", line 130, in reroute
    if platform in platform_dict.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1822, in handle_user_exception
    return handler(e)
  File "appl.py", line 191, in exceptions
    return make_response(e , 405)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/helpers.py", line 223, in make_response
    return current_app.make_response(args)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 2131, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a AttributeError.

[2020-May-20 03:34] 36.73.28.12 GET http /robots.txt? 405 METHOD NOT ALLOWED
[2020-May-20 03:34] 36.73.28.12 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "appl.py", line 130, in reroute
    if platform in platform_dict.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'

[2020-May-20 03:34] 36.73.28.12 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "appl.py", line 130, in reroute
    if platform in platform_dict.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1822, in handle_user_exception
    return handler(e)
  File "appl.py", line 191, in exceptions
    return make_response(e , 405)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/helpers.py", line 223, in make_response
    return current_app.make_response(args)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 2131, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a AttributeError.

[2020-May-20 03:34] 36.73.28.12 GET http /favicon.ico? 405 METHOD NOT ALLOWED
[2020-May-20 03:37] 36.73.28.12 POST http /? 200 OK
[2020-May-20 03:37] 36.73.28.12 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "appl.py", line 130, in reroute
    if platform in platform_dict.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'

[2020-May-20 03:37] 36.73.28.12 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "appl.py", line 130, in reroute
    if platform in platform_dict.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1822, in handle_user_exception
    return handler(e)
  File "appl.py", line 191, in exceptions
    return make_response(e , 405)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/helpers.py", line 223, in make_response
    return current_app.make_response(args)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 2131, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a AttributeError.

[2020-May-20 03:37] 36.73.28.12 GET http /favicon.ico? 405 METHOD NOT ALLOWED
[2020-May-20 03:38] 36.73.28.12 POST http /? 200 OK
[2020-May-20 03:38] 36.73.28.12 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "appl.py", line 130, in reroute
    if platform in platform_dict.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'

[2020-May-20 03:38] 36.73.28.12 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "appl.py", line 130, in reroute
    if platform in platform_dict.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1822, in handle_user_exception
    return handler(e)
  File "appl.py", line 191, in exceptions
    return make_response(e , 405)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/helpers.py", line 223, in make_response
    return current_app.make_response(args)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 2131, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a AttributeError.

[2020-May-20 03:38] 36.73.28.12 GET http /favicon.ico? 405 METHOD NOT ALLOWED
[2020-May-20 04:11] 36.65.144.197 GET http /? 200 OK
[2020-May-20 04:11] 36.65.144.197 GET http /? 200 OK
[2020-May-20 06:49] 223.71.167.163 GET http /? 200 OK
[2020-May-20 10:16] 36.65.144.197 GET http /? 200 OK
[2020-May-20 10:24] 36.65.144.197 GET http /? 200 OK
[2020-May-20 12:18] 36.65.144.197 GET http /? 200 OK
[2020-May-20 21:17] 209.17.96.250 GET http /? 200 OK
[2020-May-21 01:15] 209.17.96.82 GET http /? 200 OK
[2020-May-21 04:30] 54.183.210.5 GET http /? 200 OK
[2020-May-21 18:25] 209.17.97.114 GET http /? 200 OK
[2020-May-21 18:53] 71.6.146.186 GET http /? 200 OK
[2020-May-21 18:53] 71.6.146.186 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "appl.py", line 130, in reroute
    if platform in platform_dict.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'

[2020-May-21 18:53] 71.6.146.186 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "appl.py", line 130, in reroute
    if platform in platform_dict.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1822, in handle_user_exception
    return handler(e)
  File "appl.py", line 191, in exceptions
    return make_response(e , 405)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/helpers.py", line 223, in make_response
    return current_app.make_response(args)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 2131, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a AttributeError.

[2020-May-21 18:53] 71.6.146.186 GET http /favicon.ico? 405 METHOD NOT ALLOWED
[2020-May-21 22:03] 94.102.49.193 GET http /? 200 OK
[2020-May-21 22:03] 94.102.49.193 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "appl.py", line 130, in reroute
    if platform in platform_dict.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'

[2020-May-21 22:03] 94.102.49.193 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "appl.py", line 130, in reroute
    if platform in platform_dict.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1822, in handle_user_exception
    return handler(e)
  File "appl.py", line 191, in exceptions
    return make_response(e , 405)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/helpers.py", line 223, in make_response
    return current_app.make_response(args)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 2131, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a AttributeError.

[2020-May-21 22:03] 94.102.49.193 GET http /favicon.ico? 405 METHOD NOT ALLOWED
[2020-May-21 22:03] 35.187.98.101 GET http /? 200 OK
[2020-May-21 22:47] 209.17.96.66 GET http /? 200 OK
[2020-May-22 07:47] 39.104.121.57 GET http /? 200 OK
[2020-May-22 07:47] 39.104.121.57 GET http /? 200 OK
[2020-May-22 07:47] 39.104.175.103 POST http /onvif/device_service? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/werkzeug/routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

[2020-May-22 07:47] 39.104.175.103 POST http /onvif/device_service? 405 METHOD NOT ALLOWED
[2020-May-22 09:26] 92.118.161.57 GET http /? 200 OK
[2020-May-22 10:36] 66.240.192.138 GET http /? 200 OK
[2020-May-22 10:36] 66.240.192.138 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "appl.py", line 130, in reroute
    if platform in platform_dict.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'

[2020-May-22 10:36] 66.240.192.138 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "appl.py", line 130, in reroute
    if platform in platform_dict.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1822, in handle_user_exception
    return handler(e)
  File "appl.py", line 191, in exceptions
    return make_response(e , 405)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/helpers.py", line 223, in make_response
    return current_app.make_response(args)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 2131, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a AttributeError.

[2020-May-22 10:36] 66.240.192.138 GET http /favicon.ico? 405 METHOD NOT ALLOWED
[2020-May-22 11:14] 35.205.219.55 GET http /? 200 OK
[2020-May-22 19:10] 196.52.43.106 GET http /? 200 OK
[2020-May-23 03:13] 209.17.96.218 GET http /? 200 OK
[2020-May-23 03:53] 209.17.97.42 GET http /? 200 OK
[2020-May-23 23:29] 209.17.97.90 GET http /? 200 OK
[2020-May-24 00:43] 209.17.97.106 GET http /? 200 OK
[2020-May-24 22:06] 209.17.96.82 GET http /? 200 OK
[2020-May-25 00:34] 209.17.96.162 GET http /? 200 OK
[2020-May-26 02:45] 209.17.96.50 GET http /? 200 OK
[2020-May-26 02:47] 209.17.96.242 GET http /? 200 OK
[2020-May-26 06:26] 223.71.167.163 GET http /? 200 OK
[2020-May-26 12:04] 39.104.173.109 GET http /? 200 OK
[2020-May-26 12:04] 39.104.173.109 GET http /? 200 OK
[2020-May-26 12:04] 39.104.73.117 POST http /onvif/device_service? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/werkzeug/routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

[2020-May-26 12:04] 39.104.73.117 POST http /onvif/device_service? 405 METHOD NOT ALLOWED
[2020-May-26 16:42] 196.52.43.64 GET http /? 200 OK
[2020-May-26 20:04] 209.17.97.10 GET http /? 200 OK
[2020-May-26 20:08] 196.52.43.59 GET http /? 200 OK
[2020-May-27 00:03] 209.17.96.154 GET http /? 200 OK
[2020-May-27 04:39] 36.65.188.112 GET http /? 200 OK
[2020-May-27 04:39] 36.65.188.112 GET http /static/css/skeleton.css? 200 OK
[2020-May-27 04:39] 36.65.188.112 GET http /static/css/main.css? 200 OK
[2020-May-27 04:39] 36.65.188.112 GET http /static/css/normalize.css? 200 OK
[2020-May-27 04:39] 36.65.188.112 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "appl.py", line 130, in reroute
    if platform in platform_dict.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'

[2020-May-27 04:39] 36.65.188.112 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "appl.py", line 130, in reroute
    if platform in platform_dict.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1822, in handle_user_exception
    return handler(e)
  File "appl.py", line 191, in exceptions
    return make_response(e , 405)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/helpers.py", line 223, in make_response
    return current_app.make_response(args)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 2131, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a AttributeError.

[2020-May-27 04:39] 36.65.188.112 GET http /favicon.ico? 405 METHOD NOT ALLOWED
[2020-May-27 04:40] 36.65.188.112 POST http /? 200 OK
[2020-May-27 04:40] 36.65.188.112 POST http /? 200 OK
[2020-May-27 15:07] 36.65.188.112 POST http /? 200 OK
[2020-May-27 20:36] 209.17.97.58 GET http /? 200 OK
[2020-May-28 02:56] 209.17.96.194 GET http /? 200 OK
[2020-May-28 21:50] 36.73.34.65 GET http /? 200 OK
[2020-May-29 00:43] 209.17.97.82 GET http /? 200 OK
[2020-May-29 01:19] 162.243.144.172 GET http /? 200 OK
[2020-May-29 06:08] 209.17.97.18 GET http /? 200 OK
[2020-May-29 13:02] 185.173.35.61 GET http /? 200 OK
[2020-May-29 15:33] 213.217.0.184 GET http /photo/p/api/album.php? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/werkzeug/routing.py", line 1945, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

[2020-May-29 15:33] 213.217.0.184 GET http /photo/p/api/album.php? 405 METHOD NOT ALLOWED
[2020-May-29 18:21] 209.17.97.58 GET http /? 200 OK
