[2017-Jul-14 12:46] 127.0.0.1 GET http /? 200 OK
[2017-Jul-14 12:46] 127.0.0.1 GET http /static/css/skeleton.css? 304 NOT MODIFIED
[2017-Jul-14 12:46] 127.0.0.1 GET http /static/css/normalize.css? 304 NOT MODIFIED
[2017-Jul-14 12:46] 127.0.0.1 GET http /static/css/main.css? 304 NOT MODIFIED
[2017-Jul-14 12:46] 127.0.0.1 GET http /favicon.ico? 404 NOT FOUND
[2017-Jul-14 12:46] 127.0.0.1 GET http /favicon.ico? 404 NOT FOUND
[2017-Jul-14 12:46] 127.0.0.1 GET http /analytics/bb? 200 OK
[2017-Jul-14 12:49] 127.0.0.1 GET http /? 200 OK
[2020-May-18 08:39] 36.73.34.62 GET http /? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 66, in index
    cursor.execute(list_sql)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'hanoman.WEB_URL' doesn't exist")

[2020-May-18 08:39] 36.73.34.62 GET http /? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 66, in index
    cursor.execute(list_sql)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'hanoman.WEB_URL' doesn't exist")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1822, in handle_user_exception
    return handler(e)
  File "app.py", line 191, in exceptions
    return make_response(e , 405)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/helpers.py", line 223, in make_response
    return current_app.make_response(args)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 2131, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a ProgrammingError.

[2020-May-18 08:39] 36.73.34.62 GET http /? 405 METHOD NOT ALLOWED
[2020-May-18 08:39] 36.73.34.62 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 130, in reroute
    if platform in platform_dict.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'

[2020-May-18 08:39] 36.73.34.62 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 130, in reroute
    if platform in platform_dict.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1822, in handle_user_exception
    return handler(e)
  File "app.py", line 191, in exceptions
    return make_response(e , 405)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/helpers.py", line 223, in make_response
    return current_app.make_response(args)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 2131, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a AttributeError.

[2020-May-18 08:39] 36.73.34.62 GET http /favicon.ico? 405 METHOD NOT ALLOWED
[2020-May-18 08:48] 36.73.34.62 GET http /? 200 OK
[2020-May-18 08:48] 36.73.34.62 GET http /static/css/normalize.css? 200 OK
[2020-May-18 08:48] 36.73.34.62 GET http /static/css/main.css? 200 OK
[2020-May-18 08:48] 36.73.34.62 GET http /static/css/skeleton.css? 200 OK
[2020-May-18 08:52] 36.73.34.62 GET http /? 200 OK
[2020-May-18 08:52] 36.73.34.62 GET http /static/css/skeleton.css? 200 OK
[2020-May-18 08:52] 36.73.34.62 GET http /static/css/normalize.css? 200 OK
[2020-May-18 08:52] 36.73.34.62 GET http /static/css/main.css? 200 OK
[2020-May-18 08:52] 36.73.34.62 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 130, in reroute
    if platform in platform_dict.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'

[2020-May-18 08:52] 36.73.34.62 GET http /favicon.ico? 5xx INTERNAL SERVER ERROR
Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 130, in reroute
    if platform in platform_dict.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 1822, in handle_user_exception
    return handler(e)
  File "app.py", line 191, in exceptions
    return make_response(e , 405)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/helpers.py", line 223, in make_response
    return current_app.make_response(args)
  File "/home/hanoman/.envshorty/lib/python3.6/site-packages/flask/app.py", line 2131, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a AttributeError.

[2020-May-18 08:52] 36.73.34.62 GET http /favicon.ico? 405 METHOD NOT ALLOWED
[2020-May-18 08:54] 36.73.34.62 GET http /? 200 OK
[2020-May-18 08:54] 36.73.34.62 GET http /? 200 OK
[2020-May-18 08:57] 36.73.34.62 POST http /? 200 OK
[2020-May-18 08:57] 36.73.34.62 POST http /? 200 OK
[2020-May-18 08:57] 36.73.34.62 GET http /? 200 OK
[2020-May-18 08:58] 36.73.34.62 POST http /? 200 OK
[2020-May-18 09:01] 36.73.34.62 GET http /? 200 OK
[2020-May-18 09:01] 36.73.34.62 POST http /? 200 OK
